# Generated by Django 4.1.3 on 2023-04-05 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
        migrations.RemoveField(
            model_name='taskasinee',
            name='assign_by',
        ),
        migrations.RemoveField(
            model_name='taskasinee',
            name='assign_task',
        ),
        migrations.AddField(
            model_name='task',
            name='assign_to',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.taskasinee'),
        ),
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.project'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.taskasinee'),
        ),
    ]
