# Generated by Django 4.1.3 on 2023-04-05 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_task_user_remove_taskasinee_assign_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskasinee',
            name='language',
            field=models.CharField(choices=[('react', 'REACT'), ('python', 'PYTHON'), ('node', 'NODE'), ('angular', 'ANGULAR')], default='react', max_length=255),
        ),
    ]
