# Generated by Django 4.2 on 2023-04-06 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_task'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permission',
            options={},
        ),
        migrations.AlterField(
            model_name='permission',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
