# Generated by Django 4.2 on 2023-04-13 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_permission_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permission',
            old_name='work',
            new_name='work_on',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='project',
        ),
    ]
