# Generated by Django 4.2 on 2023-04-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_work_permission_work_on_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='project',
        ),
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ManyToManyField(default=789654, to='api.project'),
        ),
    ]
