# Generated by Django 4.2 on 2023-04-06 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_permission_options_alter_permission_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assign_to',
        ),
        migrations.DeleteModel(
            name='taskAsinee',
        ),
    ]
