# Generated by Django 4.2 on 2023-04-13 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_task_project_task_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permission',
            old_name='work_on',
            new_name='project',
        ),
    ]
