# Generated by Django 4.2 on 2023-04-12 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_permission_description_permission_can_create_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='project',
        ),
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(default=789654, on_delete=django.db.models.deletion.CASCADE, to='api.project'),
        ),
    ]
